steps:
- name: node:16-alpine
  args: ['yarn']
- name: node:16-alpine
  args: ['yarn', 'build']
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args: ['scripts/print-config.sh']
  waitFor: ['-']
  id: config
options:
  logging: CLOUD_LOGGING_ONLY
