steps:
- name: node:16-alpine
  args: ['yarn']
  id: install

- name: node:16-alpine
  args: ['yarn', 'build:app']
  waitFor: install
  id: build-app

- name: node:16-alpine
  args: ['yarn', 'build:service']
  waitFor: install
  id: build-service

- name: node:16-alpine
  args: ['yarn', 'build:proxy']
  waitFor: install
  id: build-proxy